### ISSUE TITLE
Stopwatch getLaps method should return a copy of the array

### ISSUE THREAD

**Issue by gabrielperales** [Kata-Martagon/StopWatch#23]
[Here](https://github.com/Kata-Martagon/StopWatch/blob/master/src/StopWatch.js#L93):

``` javascript
StopWatch.prototype.getLaps = function () {
  return this._lapsArray;
};
```

I think this method might be better returning `this._lapsArray.slice()` which returns a copy of the original array instead of the original array, otherwise it has no sense to have `_lapsArray` as a private attribute.

**Comment by matthewglover** [comment]
Removed getLaps() method but have used the .slice() in the publish method.
